name: Terraform

on:
  push:
    branches:
      - main
  pull_request: null

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.8

      - name: Terraform Format
        run: terraform fmt ./terraform

      - name: Terraform Init
        run: terraform init ./terraform

      - name: Terraform Validate
        run: terraform validate ./terraform

      - name: Terraform Plan
        run: terraform plan ./terraform

      - name: Create Environment File
        id: envfile
        run: |
          echo "TF_ACTIONS_WORKING_DIR=./terraform" >> $GITHUB_ENV

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        uses: hashicorp/terraform-action@v0.14.8
        with:
          subcommand: apply
          working-dir: ${{ steps.envfile.outputs.envpath }}
