
name: Terraform

on:
  push:
    branches:
      - main
  pull_request: null

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform Format
        run: |
          cd ./terraform
          terraform fmt

      - name: Terraform Init
        run: |
          cd ./terraform
          terraform init

      - name: Terraform Validate
        run: |
          cd ./terraform
          terraform validate

      - name: Terraform Plan
        run: |
          cd ./terraform
          terraform plan

      - name: Create Environment File
        id: envfile
        run: |
          echo "TF_ACTIONS_WORKING_DIR=./terraform" >> $GITHUB_ENV

      - name: Terraform Apply -auto-approve
        if: github.ref == 'refs/heads/main'
        run: |
          cd ./terraform
          terraform apply
